#!/bin/bash

if [ x$2 == x ]
then
    s_day=$1
    e_day=$1
else
    s_day=$2
    e_day=$2
fi

if [ x$1 == x ]
then
    s_day=`$HOME/code/tools/newdb_tools/yesterday.sh`
    e_day=`$HOME/code/tools/newdb_tools/yesterday.sh`
else
    s_day=$1

fi

first=$s_day
second=$e_day

second=`date -d "${second} +1 day" +%Y-%m-%d`
while [ $first != $second ]
do

/root/code/tools/newdb_tools/ss_launcher.js  --path=/root/code/tools/newdb_tools/hxddz.bs/ad_remain/ss_ad_remain  --log=/home/data/log/hxddz/ad_remain --date=$first --src=ad_login1  --topo='ad_remain2,ad_remain3,ad_remain4,ad_remain5,ad_remain6,ad_remain7,ad_remain8,ad_remain9'
/root/code/tools/newdb_tools/ss_launcher.js  --path=/root/code/tools/newdb_tools/hxddz.bs/ad_remain/ss_ad_remain  --log=/home/data/log/hxddz/ad_remain --date=$first --src=ad_login1  --topo='ad_remain10,ad_remain11,ad_remain12,ad_remain13,ad_remain14,ad_remain15,ad_remain16,ad_remain17,ad_remain18'
/root/code/tools/newdb_tools/ss_launcher.js  --path=/root/code/tools/newdb_tools/hxddz.bs/ad_remain/ss_ad_remain  --log=/home/data/log/hxddz/ad_remain --date=$first --src=ad_login1  --topo='ad_remain19,ad_remain20,ad_remain21,ad_remain22,ad_remain23,ad_remain24,ad_remain25,ad_remain26,ad_remain27'
/root/code/tools/newdb_tools/ss_launcher.js  --path=/root/code/tools/newdb_tools/hxddz.bs/ad_remain/ss_ad_remain  --log=/home/data/log/hxddz/ad_remain --date=$first --src=ad_login1  --topo='ad_remain28,ad_remain29,ad_remain30,ad_remain31,ad_remain32,ad_remain33,ad_remain34,ad_remain35,ad_remain36'
/root/code/tools/newdb_tools/ss_launcher.js  --path=/root/code/tools/newdb_tools/hxddz.bs/ad_remain/ss_ad_remain  --log=/home/data/log/hxddz/ad_remain --date=$first --src=ad_login1  --topo='ad_remain37,ad_remain38,ad_remain39,ad_remain40,ad_remain41,ad_remain42,ad_remain43,ad_remain44,ad_remain45'
/root/code/tools/newdb_tools/ss_launcher.js  --path=/root/code/tools/newdb_tools/hxddz.bs/ad_remain/ss_ad_remain  --log=/home/data/log/hxddz/ad_remain --date=$first --src=ad_login1  --topo='ad_remain46,ad_remain47,ad_remain48,ad_remain49,ad_remain50,ad_remain51,ad_remain52,ad_remain53,ad_remain54'
/root/code/tools/newdb_tools/ss_launcher.js  --path=/root/code/tools/newdb_tools/hxddz.bs/ad_remain/ss_ad_remain  --log=/home/data/log/hxddz/ad_remain --date=$first --src=ad_login1  --topo='ad_remain55,ad_remain56,ad_remain57,ad_remain58,ad_remain59,ad_remain60,ad_remain61,ad_remain62,ad_remain63'
/root/code/tools/newdb_tools/ss_launcher.js  --path=/root/code/tools/newdb_tools/hxddz.bs/ad_remain/ss_ad_remain  --log=/home/data/log/hxddz/ad_remain --date=$first --src=ad_login1  --topo='ad_remain64,ad_remain65,ad_remain66,ad_remain67,ad_remain68,ad_remain69,ad_remain70,ad_remain71,ad_remain72'
/root/code/tools/newdb_tools/ss_launcher.js  --path=/root/code/tools/newdb_tools/hxddz.bs/ad_remain/ss_ad_remain  --log=/home/data/log/hxddz/ad_remain --date=$first --src=ad_login1  --topo='ad_remain73,ad_remain74,ad_remain75,ad_remain76,ad_remain77,ad_remain78,ad_remain79,ad_remain80,ad_remain81'
/root/code/tools/newdb_tools/ss_launcher.js  --path=/root/code/tools/newdb_tools/hxddz.bs/ad_remain/ss_ad_remain  --log=/home/data/log/hxddz/ad_remain --date=$first --src=ad_login1  --topo='ad_remain82,ad_remain83,ad_remain84,ad_remain85,ad_remain86,ad_remain87,ad_remain88,ad_remain89,ad_remain90'
/root/code/tools/newdb_tools/ss_launcher.js  --path=/root/code/tools/newdb_tools/hxddz.bs/ad_remain/ss_ad_remain  --log=/home/data/log/hxddz/ad_remain --date=$first --src=ad_login1  --topo='ad_remain91,ad_remain92,ad_remain93,ad_remain94,ad_remain95,ad_remain96,ad_remain97,ad_remain98,ad_remain99'
/root/code/tools/newdb_tools/ss_launcher.js  --path=/root/code/tools/newdb_tools/hxddz.bs/ad_remain/ss_ad_remain  --log=/home/data/log/hxddz/ad_remain --date=$first --src=ad_login1  --topo='ad_remain100,ad_remain101,ad_remain102,ad_remain103,ad_remain104,ad_remain105,ad_remain106,ad_remain107,ad_remain108'
/root/code/tools/newdb_tools/ss_launcher.js  --path=/root/code/tools/newdb_tools/hxddz.bs/ad_remain/ss_ad_remain  --log=/home/data/log/hxddz/ad_remain --date=$first --src=ad_login1  --topo='ad_remain109,ad_remain110,ad_remain111,ad_remain112,ad_remain113,ad_remain114,ad_remain115,ad_remain116,ad_remain117'
/root/code/tools/newdb_tools/ss_launcher.js  --path=/root/code/tools/newdb_tools/hxddz.bs/ad_remain/ss_ad_remain  --log=/home/data/log/hxddz/ad_remain --date=$first --src=ad_login1  --topo='ad_remain118,ad_remain119,ad_remain120,ad_remain121,ad_remain122,ad_remain123,ad_remain124,ad_remain125,ad_remain126'
/root/code/tools/newdb_tools/ss_launcher.js  --path=/root/code/tools/newdb_tools/hxddz.bs/ad_remain/ss_ad_remain  --log=/home/data/log/hxddz/ad_remain --date=$first --src=ad_login1  --topo='ad_remain127,ad_remain128,ad_remain129,ad_remain130,ad_remain131,ad_remain132,ad_remain133,ad_remain134,ad_remain135'
/root/code/tools/newdb_tools/ss_launcher.js  --path=/root/code/tools/newdb_tools/hxddz.bs/ad_remain/ss_ad_remain  --log=/home/data/log/hxddz/ad_remain --date=$first --src=ad_login1  --topo='ad_remain136,ad_remain137,ad_remain138,ad_remain139,ad_remain140,ad_remain141,ad_remain142,ad_remain143,ad_remain144'
/root/code/tools/newdb_tools/ss_launcher.js  --path=/root/code/tools/newdb_tools/hxddz.bs/ad_remain/ss_ad_remain  --log=/home/data/log/hxddz/ad_remain --date=$first --src=ad_login1  --topo='ad_remain145,ad_remain146,ad_remain147,ad_remain148,ad_remain149,ad_remain150,ad_remain151,ad_remain152,ad_remain153'
/root/code/tools/newdb_tools/ss_launcher.js  --path=/root/code/tools/newdb_tools/hxddz.bs/ad_remain/ss_ad_remain  --log=/home/data/log/hxddz/ad_remain --date=$first --src=ad_login1  --topo='ad_remain154,ad_remain155,ad_remain156,ad_remain157,ad_remain158,ad_remain159,ad_remain160,ad_remain161,ad_remain162'
/root/code/tools/newdb_tools/ss_launcher.js  --path=/root/code/tools/newdb_tools/hxddz.bs/ad_remain/ss_ad_remain  --log=/home/data/log/hxddz/ad_remain --date=$first --src=ad_login1  --topo='ad_remain163,ad_remain164,ad_remain165,ad_remain166,ad_remain167,ad_remain168,ad_remain169,ad_remain170,ad_remain171'
/root/code/tools/newdb_tools/ss_launcher.js  --path=/root/code/tools/newdb_tools/hxddz.bs/ad_remain/ss_ad_remain  --log=/home/data/log/hxddz/ad_remain --date=$first --src=ad_login1  --topo='ad_remain172,ad_remain173,ad_remain174,ad_remain175,ad_remain176,ad_remain177,ad_remain178,ad_remain179,ad_remain180'
/root/code/tools/newdb_tools/ss_launcher.js  --path=/root/code/tools/newdb_tools/hxddz.bs/ad_remain/ss_ad_remain  --log=/home/data/log/hxddz/ad_remain --date=$first --src=ad_login1  --topo='ad_remain181,ad_remain182,ad_remain183,ad_remain184,ad_remain185,ad_remain186,ad_remain187,ad_remain188,ad_remain189'
/root/code/tools/newdb_tools/ss_launcher.js  --path=/root/code/tools/newdb_tools/hxddz.bs/ad_remain/ss_ad_remain  --log=/home/data/log/hxddz/ad_remain --date=$first --src=ad_login1  --topo='ad_remain190,ad_remain191,ad_remain192,ad_remain193,ad_remain194,ad_remain195,ad_remain196,ad_remain197,ad_remain198'
/root/code/tools/newdb_tools/ss_launcher.js  --path=/root/code/tools/newdb_tools/hxddz.bs/ad_remain/ss_ad_remain  --log=/home/data/log/hxddz/ad_remain --date=$first --src=ad_login1  --topo='ad_remain199,ad_remain200,ad_remain201,ad_remain202,ad_remain203,ad_remain204,ad_remain205,ad_remain206,ad_remain207'
/root/code/tools/newdb_tools/ss_launcher.js  --path=/root/code/tools/newdb_tools/hxddz.bs/ad_remain/ss_ad_remain  --log=/home/data/log/hxddz/ad_remain --date=$first --src=ad_login1  --topo='ad_remain208,ad_remain209,ad_remain210,ad_remain211,ad_remain212,ad_remain213,ad_remain214,ad_remain215,ad_remain216'
/root/code/tools/newdb_tools/ss_launcher.js  --path=/root/code/tools/newdb_tools/hxddz.bs/ad_remain/ss_ad_remain  --log=/home/data/log/hxddz/ad_remain --date=$first --src=ad_login1  --topo='ad_remain217,ad_remain218,ad_remain219,ad_remain220,ad_remain221,ad_remain222,ad_remain223,ad_remain224,ad_remain225'
/root/code/tools/newdb_tools/ss_launcher.js  --path=/root/code/tools/newdb_tools/hxddz.bs/ad_remain/ss_ad_remain  --log=/home/data/log/hxddz/ad_remain --date=$first --src=ad_login1  --topo='ad_remain226,ad_remain227,ad_remain228,ad_remain229,ad_remain230,ad_remain231,ad_remain232,ad_remain233,ad_remain234'
/root/code/tools/newdb_tools/ss_launcher.js  --path=/root/code/tools/newdb_tools/hxddz.bs/ad_remain/ss_ad_remain  --log=/home/data/log/hxddz/ad_remain --date=$first --src=ad_login1  --topo='ad_remain235,ad_remain236,ad_remain237,ad_remain238,ad_remain239,ad_remain240,ad_remain241,ad_remain242,ad_remain243'
/root/code/tools/newdb_tools/ss_launcher.js  --path=/root/code/tools/newdb_tools/hxddz.bs/ad_remain/ss_ad_remain  --log=/home/data/log/hxddz/ad_remain --date=$first --src=ad_login1  --topo='ad_remain244,ad_remain245,ad_remain246,ad_remain247,ad_remain248,ad_remain249,ad_remain250,ad_remain251,ad_remain252'
/root/code/tools/newdb_tools/ss_launcher.js  --path=/root/code/tools/newdb_tools/hxddz.bs/ad_remain/ss_ad_remain  --log=/home/data/log/hxddz/ad_remain --date=$first --src=ad_login1  --topo='ad_remain253,ad_remain254,ad_remain255,ad_remain256,ad_remain257,ad_remain258,ad_remain259,ad_remain260,ad_remain261'
/root/code/tools/newdb_tools/ss_launcher.js  --path=/root/code/tools/newdb_tools/hxddz.bs/ad_remain/ss_ad_remain  --log=/home/data/log/hxddz/ad_remain --date=$first --src=ad_login1  --topo='ad_remain262,ad_remain263,ad_remain264,ad_remain265,ad_remain266,ad_remain267,ad_remain268,ad_remain269,ad_remain270'
/root/code/tools/newdb_tools/ss_launcher.js  --path=/root/code/tools/newdb_tools/hxddz.bs/ad_remain/ss_ad_remain  --log=/home/data/log/hxddz/ad_remain --date=$first --src=ad_login1  --topo='ad_remain271,ad_remain272,ad_remain273,ad_remain274,ad_remain275,ad_remain276,ad_remain277,ad_remain278,ad_remain279'
/root/code/tools/newdb_tools/ss_launcher.js  --path=/root/code/tools/newdb_tools/hxddz.bs/ad_remain/ss_ad_remain  --log=/home/data/log/hxddz/ad_remain --date=$first --src=ad_login1  --topo='ad_remain280,ad_remain281,ad_remain282,ad_remain283,ad_remain284,ad_remain285,ad_remain286,ad_remain287,ad_remain288'
/root/code/tools/newdb_tools/ss_launcher.js  --path=/root/code/tools/newdb_tools/hxddz.bs/ad_remain/ss_ad_remain  --log=/home/data/log/hxddz/ad_remain --date=$first --src=ad_login1  --topo='ad_remain289,ad_remain290,ad_remain291,ad_remain292,ad_remain293,ad_remain294,ad_remain295,ad_remain296,ad_remain297'
/root/code/tools/newdb_tools/ss_launcher.js  --path=/root/code/tools/newdb_tools/hxddz.bs/ad_remain/ss_ad_remain  --log=/home/data/log/hxddz/ad_remain --date=$first --src=ad_login1  --topo='ad_remain298,ad_remain299,ad_remain300,ad_remain301,ad_remain302,ad_remain303,ad_remain304,ad_remain305,ad_remain306'
/root/code/tools/newdb_tools/ss_launcher.js  --path=/root/code/tools/newdb_tools/hxddz.bs/ad_remain/ss_ad_remain  --log=/home/data/log/hxddz/ad_remain --date=$first --src=ad_login1  --topo='ad_remain307,ad_remain308,ad_remain309,ad_remain310,ad_remain311,ad_remain312,ad_remain313,ad_remain314,ad_remain315'
/root/code/tools/newdb_tools/ss_launcher.js  --path=/root/code/tools/newdb_tools/hxddz.bs/ad_remain/ss_ad_remain  --log=/home/data/log/hxddz/ad_remain --date=$first --src=ad_login1  --topo='ad_remain316,ad_remain317,ad_remain318,ad_remain319,ad_remain320,ad_remain321,ad_remain322,ad_remain323,ad_remain324'
/root/code/tools/newdb_tools/ss_launcher.js  --path=/root/code/tools/newdb_tools/hxddz.bs/ad_remain/ss_ad_remain  --log=/home/data/log/hxddz/ad_remain --date=$first --src=ad_login1  --topo='ad_remain325,ad_remain326,ad_remain327,ad_remain328,ad_remain329,ad_remain330,ad_remain331,ad_remain332,ad_remain333'
/root/code/tools/newdb_tools/ss_launcher.js  --path=/root/code/tools/newdb_tools/hxddz.bs/ad_remain/ss_ad_remain  --log=/home/data/log/hxddz/ad_remain --date=$first --src=ad_login1  --topo='ad_remain334,ad_remain335,ad_remain336,ad_remain337,ad_remain338,ad_remain339,ad_remain340,ad_remain341,ad_remain342'
/root/code/tools/newdb_tools/ss_launcher.js  --path=/root/code/tools/newdb_tools/hxddz.bs/ad_remain/ss_ad_remain  --log=/home/data/log/hxddz/ad_remain --date=$first --src=ad_login1  --topo='ad_remain343,ad_remain344,ad_remain345,ad_remain346,ad_remain347,ad_remain348,ad_remain349,ad_remain350,ad_remain351'
/root/code/tools/newdb_tools/ss_launcher.js  --path=/root/code/tools/newdb_tools/hxddz.bs/ad_remain/ss_ad_remain  --log=/home/data/log/hxddz/ad_remain --date=$first --src=ad_login1  --topo='ad_remain352,ad_remain353,ad_remain354,ad_remain355,ad_remain356,ad_remain357,ad_remain358,ad_remain359,ad_remain360'
echo $first===ad_remain

/root/code/tools/newdb_tools/ss_launcher.js  --path=/root/code/tools/newdb_tools/hxddz.bs/ad_remain/ss_ios_ad_remain --log=/home/data/log/hxddz/ad_remain --date=$first --src=login1 --topo="ios_ad_remain2,ios_ad_remain3,ios_ad_remain4,ios_ad_remain5,ios_ad_remain6,ios_ad_remain7,ios_ad_remain8,ios_ad_remain9,ios_ad_remain10,ios_ad_remain11,ios_ad_remain12,ios_ad_remain13,ios_ad_remain14,ios_ad_remain15,ios_ad_remain16,ios_ad_remain17,ios_ad_remain18"
/root/code/tools/newdb_tools/ss_launcher.js  --path=/root/code/tools/newdb_tools/hxddz.bs/ad_remain/ss_ios_ad_remain --log=/home/data/log/hxddz/ad_remain --date=$first --src=login1 --topo="ios_ad_remain19,ios_ad_remain20,ios_ad_remain21,ios_ad_remain22,ios_ad_remain23,ios_ad_remain24,ios_ad_remain25,ios_ad_remain26,ios_ad_remain27,ios_ad_remain28,ios_ad_remain29,ios_ad_remain30,ios_ad_remain31,ios_ad_remain32,ios_ad_remain33,ios_ad_remain34,ios_ad_remain35,ios_ad_remain36"
/root/code/tools/newdb_tools/ss_launcher.js  --path=/root/code/tools/newdb_tools/hxddz.bs/ad_remain/ss_ios_ad_remain --log=/home/data/log/hxddz/ad_remain --date=$first --src=login1 --topo="ios_ad_remain37,ios_ad_remain38,ios_ad_remain39,ios_ad_remain40,ios_ad_remain41,ios_ad_remain42,ios_ad_remain43,ios_ad_remain44,ios_ad_remain45,ios_ad_remain46,ios_ad_remain47,ios_ad_remain48,ios_ad_remain49,ios_ad_remain50,ios_ad_remain51,ios_ad_remain52,ios_ad_remain53,ios_ad_remain54"
/root/code/tools/newdb_tools/ss_launcher.js  --path=/root/code/tools/newdb_tools/hxddz.bs/ad_remain/ss_ios_ad_remain --log=/home/data/log/hxddz/ad_remain --date=$first --src=login1 --topo="ios_ad_remain55,ios_ad_remain56,ios_ad_remain57,ios_ad_remain58,ios_ad_remain59,ios_ad_remain60,ios_ad_remain61,ios_ad_remain62,ios_ad_remain63,ios_ad_remain64,ios_ad_remain65,ios_ad_remain66,ios_ad_remain67,ios_ad_remain68,ios_ad_remain69,ios_ad_remain70,ios_ad_remain71,ios_ad_remain72"
/root/code/tools/newdb_tools/ss_launcher.js  --path=/root/code/tools/newdb_tools/hxddz.bs/ad_remain/ss_ios_ad_remain --log=/home/data/log/hxddz/ad_remain --date=$first --src=login1 --topo="ios_ad_remain73,ios_ad_remain74,ios_ad_remain75,ios_ad_remain76,ios_ad_remain77,ios_ad_remain78,ios_ad_remain79,ios_ad_remain80,ios_ad_remain81,ios_ad_remain82,ios_ad_remain83,ios_ad_remain84,ios_ad_remain85,ios_ad_remain86,ios_ad_remain87,ios_ad_remain88,ios_ad_remain89,ios_ad_remain90"
/root/code/tools/newdb_tools/ss_launcher.js  --path=/root/code/tools/newdb_tools/hxddz.bs/ad_remain/ss_ios_ad_remain --log=/home/data/log/hxddz/ad_remain --date=$first --src=login1 --topo="ios_ad_remain91,ios_ad_remain92,ios_ad_remain93,ios_ad_remain94,ios_ad_remain95,ios_ad_remain96,ios_ad_remain97,ios_ad_remain98,ios_ad_remain99,ios_ad_remain100,ios_ad_remain101,ios_ad_remain102,ios_ad_remain103,ios_ad_remain104,ios_ad_remain105,ios_ad_remain106,ios_ad_remain107,ios_ad_remain108"
/root/code/tools/newdb_tools/ss_launcher.js  --path=/root/code/tools/newdb_tools/hxddz.bs/ad_remain/ss_ios_ad_remain --log=/home/data/log/hxddz/ad_remain --date=$first --src=login1 --topo="ios_ad_remain109,ios_ad_remain110,ios_ad_remain111,ios_ad_remain112,ios_ad_remain113,ios_ad_remain114,ios_ad_remain115,ios_ad_remain116,ios_ad_remain117,ios_ad_remain118,ios_ad_remain119,ios_ad_remain120,ios_ad_remain121,ios_ad_remain122,ios_ad_remain123,ios_ad_remain124,ios_ad_remain125,ios_ad_remain126"
/root/code/tools/newdb_tools/ss_launcher.js  --path=/root/code/tools/newdb_tools/hxddz.bs/ad_remain/ss_ios_ad_remain --log=/home/data/log/hxddz/ad_remain --date=$first --src=login1 --topo="ios_ad_remain127,ios_ad_remain128,ios_ad_remain129,ios_ad_remain130,ios_ad_remain131,ios_ad_remain132,ios_ad_remain133,ios_ad_remain134,ios_ad_remain135,ios_ad_remain136,ios_ad_remain137,ios_ad_remain138,ios_ad_remain139,ios_ad_remain140,ios_ad_remain141,ios_ad_remain142,ios_ad_remain143,ios_ad_remain144"
/root/code/tools/newdb_tools/ss_launcher.js  --path=/root/code/tools/newdb_tools/hxddz.bs/ad_remain/ss_ios_ad_remain --log=/home/data/log/hxddz/ad_remain --date=$first --src=login1 --topo="ios_ad_remain145,ios_ad_remain146,ios_ad_remain147,ios_ad_remain148,ios_ad_remain149,ios_ad_remain150,ios_ad_remain151,ios_ad_remain152,ios_ad_remain153,ios_ad_remain154,ios_ad_remain155,ios_ad_remain156,ios_ad_remain157,ios_ad_remain158,ios_ad_remain159,ios_ad_remain160,ios_ad_remain161,ios_ad_remain162"
/root/code/tools/newdb_tools/ss_launcher.js  --path=/root/code/tools/newdb_tools/hxddz.bs/ad_remain/ss_ios_ad_remain --log=/home/data/log/hxddz/ad_remain --date=$first --src=login1 --topo="ios_ad_remain163,ios_ad_remain164,ios_ad_remain165,ios_ad_remain166,ios_ad_remain167,ios_ad_remain168,ios_ad_remain169,ios_ad_remain170,ios_ad_remain171,ios_ad_remain172,ios_ad_remain173,ios_ad_remain174,ios_ad_remain175,ios_ad_remain176,ios_ad_remain177,ios_ad_remain178,ios_ad_remain179,ios_ad_remain180"
/root/code/tools/newdb_tools/ss_launcher.js  --path=/root/code/tools/newdb_tools/hxddz.bs/ad_remain/ss_ios_ad_remain --log=/home/data/log/hxddz/ad_remain --date=$first --src=login1 --topo="ios_ad_remain181,ios_ad_remain182,ios_ad_remain183,ios_ad_remain184,ios_ad_remain185,ios_ad_remain186,ios_ad_remain187,ios_ad_remain188,ios_ad_remain189,ios_ad_remain190,ios_ad_remain191,ios_ad_remain192,ios_ad_remain193,ios_ad_remain194,ios_ad_remain195,ios_ad_remain196,ios_ad_remain197,ios_ad_remain198"
/root/code/tools/newdb_tools/ss_launcher.js  --path=/root/code/tools/newdb_tools/hxddz.bs/ad_remain/ss_ios_ad_remain --log=/home/data/log/hxddz/ad_remain --date=$first --src=login1 --topo="ios_ad_remain199,ios_ad_remain200,ios_ad_remain201,ios_ad_remain202,ios_ad_remain203,ios_ad_remain204,ios_ad_remain205,ios_ad_remain206,ios_ad_remain207,ios_ad_remain208,ios_ad_remain209,ios_ad_remain210,ios_ad_remain211,ios_ad_remain212,ios_ad_remain213,ios_ad_remain214,ios_ad_remain215,ios_ad_remain216"
/root/code/tools/newdb_tools/ss_launcher.js  --path=/root/code/tools/newdb_tools/hxddz.bs/ad_remain/ss_ios_ad_remain --log=/home/data/log/hxddz/ad_remain --date=$first --src=login1 --topo="ios_ad_remain217,ios_ad_remain218,ios_ad_remain219,ios_ad_remain220,ios_ad_remain221,ios_ad_remain222,ios_ad_remain223,ios_ad_remain224,ios_ad_remain225,ios_ad_remain226,ios_ad_remain227,ios_ad_remain228,ios_ad_remain229,ios_ad_remain230,ios_ad_remain231,ios_ad_remain232,ios_ad_remain233,ios_ad_remain234"
/root/code/tools/newdb_tools/ss_launcher.js  --path=/root/code/tools/newdb_tools/hxddz.bs/ad_remain/ss_ios_ad_remain --log=/home/data/log/hxddz/ad_remain --date=$first --src=login1 --topo="ios_ad_remain235,ios_ad_remain236,ios_ad_remain237,ios_ad_remain238,ios_ad_remain239,ios_ad_remain240,ios_ad_remain241,ios_ad_remain242,ios_ad_remain243,ios_ad_remain244,ios_ad_remain245,ios_ad_remain246,ios_ad_remain247,ios_ad_remain248,ios_ad_remain249,ios_ad_remain250,ios_ad_remain251,ios_ad_remain252"
/root/code/tools/newdb_tools/ss_launcher.js  --path=/root/code/tools/newdb_tools/hxddz.bs/ad_remain/ss_ios_ad_remain --log=/home/data/log/hxddz/ad_remain --date=$first --src=login1 --topo="ios_ad_remain253,ios_ad_remain254,ios_ad_remain255,ios_ad_remain256,ios_ad_remain257,ios_ad_remain258,ios_ad_remain259,ios_ad_remain260,ios_ad_remain261,ios_ad_remain262,ios_ad_remain263,ios_ad_remain264,ios_ad_remain265,ios_ad_remain266,ios_ad_remain267,ios_ad_remain268,ios_ad_remain269,ios_ad_remain270"
/root/code/tools/newdb_tools/ss_launcher.js  --path=/root/code/tools/newdb_tools/hxddz.bs/ad_remain/ss_ios_ad_remain --log=/home/data/log/hxddz/ad_remain --date=$first --src=login1 --topo="ios_ad_remain271,ios_ad_remain272,ios_ad_remain273,ios_ad_remain274,ios_ad_remain275,ios_ad_remain276,ios_ad_remain277,ios_ad_remain278,ios_ad_remain279,ios_ad_remain280,ios_ad_remain281,ios_ad_remain282,ios_ad_remain283,ios_ad_remain284,ios_ad_remain285,ios_ad_remain286,ios_ad_remain287,ios_ad_remain288"
/root/code/tools/newdb_tools/ss_launcher.js  --path=/root/code/tools/newdb_tools/hxddz.bs/ad_remain/ss_ios_ad_remain --log=/home/data/log/hxddz/ad_remain --date=$first --src=login1 --topo="ios_ad_remain289,ios_ad_remain290,ios_ad_remain291,ios_ad_remain292,ios_ad_remain293,ios_ad_remain294,ios_ad_remain295,ios_ad_remain296,ios_ad_remain297,ios_ad_remain298,ios_ad_remain299,ios_ad_remain300,ios_ad_remain301,ios_ad_remain302,ios_ad_remain303,ios_ad_remain304,ios_ad_remain305,ios_ad_remain306"
/root/code/tools/newdb_tools/ss_launcher.js  --path=/root/code/tools/newdb_tools/hxddz.bs/ad_remain/ss_ios_ad_remain --log=/home/data/log/hxddz/ad_remain --date=$first --src=login1 --topo="ios_ad_remain307,ios_ad_remain308,ios_ad_remain309,ios_ad_remain310,ios_ad_remain311,ios_ad_remain312,ios_ad_remain313,ios_ad_remain314,ios_ad_remain315,ios_ad_remain316,ios_ad_remain317,ios_ad_remain318,ios_ad_remain319,ios_ad_remain320,ios_ad_remain321,ios_ad_remain322,ios_ad_remain323,ios_ad_remain324"
/root/code/tools/newdb_tools/ss_launcher.js  --path=/root/code/tools/newdb_tools/hxddz.bs/ad_remain/ss_ios_ad_remain --log=/home/data/log/hxddz/ad_remain --date=$first --src=login1 --topo="ios_ad_remain325,ios_ad_remain326,ios_ad_remain327,ios_ad_remain328,ios_ad_remain329,ios_ad_remain330,ios_ad_remain331,ios_ad_remain332,ios_ad_remain333,ios_ad_remain334,ios_ad_remain335,ios_ad_remain336,ios_ad_remain337,ios_ad_remain338,ios_ad_remain339,ios_ad_remain340,ios_ad_remain341,ios_ad_remain342"
/root/code/tools/newdb_tools/ss_launcher.js  --path=/root/code/tools/newdb_tools/hxddz.bs/ad_remain/ss_ios_ad_remain --log=/home/data/log/hxddz/ad_remain --date=$first --src=login1 --topo="ios_ad_remain343,ios_ad_remain344,ios_ad_remain345,ios_ad_remain346,ios_ad_remain347,ios_ad_remain348,ios_ad_remain349,ios_ad_remain350,ios_ad_remain351,ios_ad_remain352,ios_ad_remain353,ios_ad_remain354,ios_ad_remain355,ios_ad_remain356,ios_ad_remain357,ios_ad_remain358,ios_ad_remain359,ios_ad_remain360"


echo $first===ios_ad_remain
first=`date -d "${first} +1 day" +%Y-%m-%d`
done

