#!/bin/bash

if [ x$2 == x ]
then
    s_day=$1
    e_day=$1
else
    s_day=$2
    e_day=$2
fi

if [ x$1 == x ]
then
    s_day=`$HOME/code/tools/newdb_tools/yesterday.sh`
    e_day=`$HOME/code/tools/newdb_tools/yesterday.sh`
else
    s_day=$1

fi

first=$s_day
second=$e_day

second=`date -d "${second} +1 day" +%Y-%m-%d`
while [ $first != $second ]
do



/root/code/tools/newdb_tools/ss_launcher.js  --path=/root/code/tools/newdb_tools/hxddz.bs/ltvn/ss_ddz_ad_ltv --log=/home/data/log/hxddz/ltvn --date=$first   --src=ddz_pay1 --topo="ddz_ad_ltv1,ddz_ad_ltv2,ddz_ad_ltv3,ddz_ad_ltv4,ddz_ad_ltv5,ddz_ad_ltv6,ddz_ad_ltv7,ddz_ad_ltv8,ddz_ad_ltv9,ddz_ad_ltv10,ddz_ad_ltv11,ddz_ad_ltv12"
/root/code/tools/newdb_tools/ss_launcher.js  --path=/root/code/tools/newdb_tools/hxddz.bs/ltvn/ss_ddz_ad_ltv --log=/home/data/log/hxddz/ltvn --date=$first   --src=ddz_pay1 --topo="ddz_ad_ltv13,ddz_ad_ltv14,ddz_ad_ltv15,ddz_ad_ltv16,ddz_ad_ltv17,ddz_ad_ltv18,ddz_ad_ltv19,ddz_ad_ltv20,ddz_ad_ltv21,ddz_ad_ltv22,ddz_ad_ltv23,ddz_ad_ltv24"
/root/code/tools/newdb_tools/ss_launcher.js  --path=/root/code/tools/newdb_tools/hxddz.bs/ltvn/ss_ddz_ad_ltv --log=/home/data/log/hxddz/ltvn --date=$first   --src=ddz_pay1 --topo="ddz_ad_ltv25,ddz_ad_ltv26,ddz_ad_ltv27,ddz_ad_ltv28,ddz_ad_ltv29,ddz_ad_ltv30,ddz_ad_ltv31,ddz_ad_ltv32,ddz_ad_ltv33,ddz_ad_ltv34,ddz_ad_ltv35,ddz_ad_ltv36"
/root/code/tools/newdb_tools/ss_launcher.js  --path=/root/code/tools/newdb_tools/hxddz.bs/ltvn/ss_ddz_ad_ltv --log=/home/data/log/hxddz/ltvn --date=$first   --src=ddz_pay1 --topo="ddz_ad_ltv37,ddz_ad_ltv38,ddz_ad_ltv39,ddz_ad_ltv40,ddz_ad_ltv41,ddz_ad_ltv42,ddz_ad_ltv43,ddz_ad_ltv44,ddz_ad_ltv45,ddz_ad_ltv46,ddz_ad_ltv47,ddz_ad_ltv48"
/root/code/tools/newdb_tools/ss_launcher.js  --path=/root/code/tools/newdb_tools/hxddz.bs/ltvn/ss_ddz_ad_ltv --log=/home/data/log/hxddz/ltvn --date=$first   --src=ddz_pay1 --topo="ddz_ad_ltv49,ddz_ad_ltv50,ddz_ad_ltv51,ddz_ad_ltv52,ddz_ad_ltv53,ddz_ad_ltv54,ddz_ad_ltv55,ddz_ad_ltv56,ddz_ad_ltv57,ddz_ad_ltv58,ddz_ad_ltv59,ddz_ad_ltv60"
/root/code/tools/newdb_tools/ss_launcher.js  --path=/root/code/tools/newdb_tools/hxddz.bs/ltvn/ss_ddz_ad_ltv --log=/home/data/log/hxddz/ltvn --date=$first   --src=ddz_pay1 --topo="ddz_ad_ltv61,ddz_ad_ltv62,ddz_ad_ltv63,ddz_ad_ltv64,ddz_ad_ltv65,ddz_ad_ltv66,ddz_ad_ltv67,ddz_ad_ltv68,ddz_ad_ltv69,ddz_ad_ltv70,ddz_ad_ltv71,ddz_ad_ltv72"
/root/code/tools/newdb_tools/ss_launcher.js  --path=/root/code/tools/newdb_tools/hxddz.bs/ltvn/ss_ddz_ad_ltv --log=/home/data/log/hxddz/ltvn --date=$first   --src=ddz_pay1 --topo="ddz_ad_ltv73,ddz_ad_ltv74,ddz_ad_ltv75,ddz_ad_ltv76,ddz_ad_ltv77,ddz_ad_ltv78,ddz_ad_ltv79,ddz_ad_ltv80,ddz_ad_ltv81,ddz_ad_ltv82,ddz_ad_ltv83,ddz_ad_ltv84"
/root/code/tools/newdb_tools/ss_launcher.js  --path=/root/code/tools/newdb_tools/hxddz.bs/ltvn/ss_ddz_ad_ltv --log=/home/data/log/hxddz/ltvn --date=$first   --src=ddz_pay1 --topo="ddz_ad_ltv85,ddz_ad_ltv86,ddz_ad_ltv87,ddz_ad_ltv88,ddz_ad_ltv89,ddz_ad_ltv90,ddz_ad_ltv91,ddz_ad_ltv92,ddz_ad_ltv93,ddz_ad_ltv94,ddz_ad_ltv95,ddz_ad_ltv96"
/root/code/tools/newdb_tools/ss_launcher.js  --path=/root/code/tools/newdb_tools/hxddz.bs/ltvn/ss_ddz_ad_ltv --log=/home/data/log/hxddz/ltvn --date=$first   --src=ddz_pay1 --topo="ddz_ad_ltv97,ddz_ad_ltv98,ddz_ad_ltv99,ddz_ad_ltv100,ddz_ad_ltv101,ddz_ad_ltv102,ddz_ad_ltv103,ddz_ad_ltv104,ddz_ad_ltv105,ddz_ad_ltv106,ddz_ad_ltv107,ddz_ad_ltv108"
/root/code/tools/newdb_tools/ss_launcher.js  --path=/root/code/tools/newdb_tools/hxddz.bs/ltvn/ss_ddz_ad_ltv --log=/home/data/log/hxddz/ltvn --date=$first   --src=ddz_pay1 --topo="ddz_ad_ltv109,ddz_ad_ltv110,ddz_ad_ltv111,ddz_ad_ltv112,ddz_ad_ltv113,ddz_ad_ltv114,ddz_ad_ltv115,ddz_ad_ltv116,ddz_ad_ltv117,ddz_ad_ltv118,ddz_ad_ltv119,ddz_ad_ltv120"
/root/code/tools/newdb_tools/ss_launcher.js  --path=/root/code/tools/newdb_tools/hxddz.bs/ltvn/ss_ddz_ad_ltv --log=/home/data/log/hxddz/ltvn --date=$first   --src=ddz_pay1 --topo="ddz_ad_ltv121,ddz_ad_ltv122,ddz_ad_ltv123,ddz_ad_ltv124,ddz_ad_ltv125,ddz_ad_ltv126,ddz_ad_ltv127,ddz_ad_ltv128,ddz_ad_ltv129,ddz_ad_ltv130,ddz_ad_ltv131,ddz_ad_ltv132"
/root/code/tools/newdb_tools/ss_launcher.js  --path=/root/code/tools/newdb_tools/hxddz.bs/ltvn/ss_ddz_ad_ltv --log=/home/data/log/hxddz/ltvn --date=$first   --src=ddz_pay1 --topo="ddz_ad_ltv133,ddz_ad_ltv134,ddz_ad_ltv135,ddz_ad_ltv136,ddz_ad_ltv137,ddz_ad_ltv138,ddz_ad_ltv139,ddz_ad_ltv140,ddz_ad_ltv141,ddz_ad_ltv142,ddz_ad_ltv143,ddz_ad_ltv144"
/root/code/tools/newdb_tools/ss_launcher.js  --path=/root/code/tools/newdb_tools/hxddz.bs/ltvn/ss_ddz_ad_ltv --log=/home/data/log/hxddz/ltvn --date=$first   --src=ddz_pay1 --topo="ddz_ad_ltv145,ddz_ad_ltv146,ddz_ad_ltv147,ddz_ad_ltv148,ddz_ad_ltv149,ddz_ad_ltv150,ddz_ad_ltv151,ddz_ad_ltv152,ddz_ad_ltv153,ddz_ad_ltv154,ddz_ad_ltv155,ddz_ad_ltv156"
/root/code/tools/newdb_tools/ss_launcher.js  --path=/root/code/tools/newdb_tools/hxddz.bs/ltvn/ss_ddz_ad_ltv --log=/home/data/log/hxddz/ltvn --date=$first   --src=ddz_pay1 --topo="ddz_ad_ltv157,ddz_ad_ltv158,ddz_ad_ltv159,ddz_ad_ltv160,ddz_ad_ltv161,ddz_ad_ltv162,ddz_ad_ltv163,ddz_ad_ltv164,ddz_ad_ltv165,ddz_ad_ltv166,ddz_ad_ltv167,ddz_ad_ltv168"
/root/code/tools/newdb_tools/ss_launcher.js  --path=/root/code/tools/newdb_tools/hxddz.bs/ltvn/ss_ddz_ad_ltv --log=/home/data/log/hxddz/ltvn --date=$first   --src=ddz_pay1 --topo="ddz_ad_ltv169,ddz_ad_ltv170,ddz_ad_ltv171,ddz_ad_ltv172,ddz_ad_ltv173,ddz_ad_ltv174,ddz_ad_ltv175,ddz_ad_ltv176,ddz_ad_ltv177,ddz_ad_ltv178,ddz_ad_ltv179,ddz_ad_ltv180"
/root/code/tools/newdb_tools/ss_launcher.js  --path=/root/code/tools/newdb_tools/hxddz.bs/ltvn/ss_ddz_ad_ltv --log=/home/data/log/hxddz/ltvn --date=$first   --src=ddz_pay1 --topo="ddz_ad_ltv181,ddz_ad_ltv182,ddz_ad_ltv183,ddz_ad_ltv184,ddz_ad_ltv185,ddz_ad_ltv186,ddz_ad_ltv187,ddz_ad_ltv188,ddz_ad_ltv189,ddz_ad_ltv190,ddz_ad_ltv191,ddz_ad_ltv192"
/root/code/tools/newdb_tools/ss_launcher.js  --path=/root/code/tools/newdb_tools/hxddz.bs/ltvn/ss_ddz_ad_ltv --log=/home/data/log/hxddz/ltvn --date=$first   --src=ddz_pay1 --topo="ddz_ad_ltv193,ddz_ad_ltv194,ddz_ad_ltv195,ddz_ad_ltv196,ddz_ad_ltv197,ddz_ad_ltv198,ddz_ad_ltv199,ddz_ad_ltv200,ddz_ad_ltv201,ddz_ad_ltv202,ddz_ad_ltv203,ddz_ad_ltv204"
/root/code/tools/newdb_tools/ss_launcher.js  --path=/root/code/tools/newdb_tools/hxddz.bs/ltvn/ss_ddz_ad_ltv --log=/home/data/log/hxddz/ltvn --date=$first   --src=ddz_pay1 --topo="ddz_ad_ltv205,ddz_ad_ltv206,ddz_ad_ltv207,ddz_ad_ltv208,ddz_ad_ltv209,ddz_ad_ltv210,ddz_ad_ltv211,ddz_ad_ltv212,ddz_ad_ltv213,ddz_ad_ltv214,ddz_ad_ltv215,ddz_ad_ltv216"
/root/code/tools/newdb_tools/ss_launcher.js  --path=/root/code/tools/newdb_tools/hxddz.bs/ltvn/ss_ddz_ad_ltv --log=/home/data/log/hxddz/ltvn --date=$first   --src=ddz_pay1 --topo="ddz_ad_ltv217,ddz_ad_ltv218,ddz_ad_ltv219,ddz_ad_ltv220,ddz_ad_ltv221,ddz_ad_ltv222,ddz_ad_ltv223,ddz_ad_ltv224,ddz_ad_ltv225,ddz_ad_ltv226,ddz_ad_ltv227,ddz_ad_ltv228"
/root/code/tools/newdb_tools/ss_launcher.js  --path=/root/code/tools/newdb_tools/hxddz.bs/ltvn/ss_ddz_ad_ltv --log=/home/data/log/hxddz/ltvn --date=$first   --src=ddz_pay1 --topo="ddz_ad_ltv229,ddz_ad_ltv230,ddz_ad_ltv231,ddz_ad_ltv232,ddz_ad_ltv233,ddz_ad_ltv234,ddz_ad_ltv235,ddz_ad_ltv236,ddz_ad_ltv237,ddz_ad_ltv238,ddz_ad_ltv239,ddz_ad_ltv240"
/root/code/tools/newdb_tools/ss_launcher.js  --path=/root/code/tools/newdb_tools/hxddz.bs/ltvn/ss_ddz_ad_ltv --log=/home/data/log/hxddz/ltvn --date=$first   --src=ddz_pay1 --topo="ddz_ad_ltv241,ddz_ad_ltv242,ddz_ad_ltv243,ddz_ad_ltv244,ddz_ad_ltv245,ddz_ad_ltv246,ddz_ad_ltv247,ddz_ad_ltv248,ddz_ad_ltv249,ddz_ad_ltv250,ddz_ad_ltv251,ddz_ad_ltv252"
/root/code/tools/newdb_tools/ss_launcher.js  --path=/root/code/tools/newdb_tools/hxddz.bs/ltvn/ss_ddz_ad_ltv --log=/home/data/log/hxddz/ltvn --date=$first   --src=ddz_pay1 --topo="ddz_ad_ltv253,ddz_ad_ltv254,ddz_ad_ltv255,ddz_ad_ltv256,ddz_ad_ltv257,ddz_ad_ltv258,ddz_ad_ltv259,ddz_ad_ltv260,ddz_ad_ltv261,ddz_ad_ltv262,ddz_ad_ltv263,ddz_ad_ltv264"
/root/code/tools/newdb_tools/ss_launcher.js  --path=/root/code/tools/newdb_tools/hxddz.bs/ltvn/ss_ddz_ad_ltv --log=/home/data/log/hxddz/ltvn --date=$first   --src=ddz_pay1 --topo="ddz_ad_ltv265,ddz_ad_ltv266,ddz_ad_ltv267,ddz_ad_ltv268,ddz_ad_ltv269,ddz_ad_ltv270,ddz_ad_ltv271,ddz_ad_ltv272,ddz_ad_ltv273,ddz_ad_ltv274,ddz_ad_ltv275,ddz_ad_ltv276"
/root/code/tools/newdb_tools/ss_launcher.js  --path=/root/code/tools/newdb_tools/hxddz.bs/ltvn/ss_ddz_ad_ltv --log=/home/data/log/hxddz/ltvn --date=$first   --src=ddz_pay1 --topo="ddz_ad_ltv277,ddz_ad_ltv278,ddz_ad_ltv279,ddz_ad_ltv280,ddz_ad_ltv281,ddz_ad_ltv282,ddz_ad_ltv283,ddz_ad_ltv284,ddz_ad_ltv285,ddz_ad_ltv286,ddz_ad_ltv287,ddz_ad_ltv288"
/root/code/tools/newdb_tools/ss_launcher.js  --path=/root/code/tools/newdb_tools/hxddz.bs/ltvn/ss_ddz_ad_ltv --log=/home/data/log/hxddz/ltvn --date=$first   --src=ddz_pay1 --topo="ddz_ad_ltv289,ddz_ad_ltv290,ddz_ad_ltv291,ddz_ad_ltv292,ddz_ad_ltv293,ddz_ad_ltv294,ddz_ad_ltv295,ddz_ad_ltv296,ddz_ad_ltv297,ddz_ad_ltv298,ddz_ad_ltv299,ddz_ad_ltv300"
/root/code/tools/newdb_tools/ss_launcher.js  --path=/root/code/tools/newdb_tools/hxddz.bs/ltvn/ss_ddz_ad_ltv --log=/home/data/log/hxddz/ltvn --date=$first   --src=ddz_pay1 --topo="ddz_ad_ltv301,ddz_ad_ltv302,ddz_ad_ltv303,ddz_ad_ltv304,ddz_ad_ltv305,ddz_ad_ltv306,ddz_ad_ltv307,ddz_ad_ltv308,ddz_ad_ltv309,ddz_ad_ltv310,ddz_ad_ltv311,ddz_ad_ltv312"
/root/code/tools/newdb_tools/ss_launcher.js  --path=/root/code/tools/newdb_tools/hxddz.bs/ltvn/ss_ddz_ad_ltv --log=/home/data/log/hxddz/ltvn --date=$first   --src=ddz_pay1 --topo="ddz_ad_ltv313,ddz_ad_ltv314,ddz_ad_ltv315,ddz_ad_ltv316,ddz_ad_ltv317,ddz_ad_ltv318,ddz_ad_ltv319,ddz_ad_ltv320,ddz_ad_ltv321,ddz_ad_ltv322,ddz_ad_ltv323,ddz_ad_ltv324"
/root/code/tools/newdb_tools/ss_launcher.js  --path=/root/code/tools/newdb_tools/hxddz.bs/ltvn/ss_ddz_ad_ltv --log=/home/data/log/hxddz/ltvn --date=$first   --src=ddz_pay1 --topo="ddz_ad_ltv325,ddz_ad_ltv326,ddz_ad_ltv327,ddz_ad_ltv328,ddz_ad_ltv329,ddz_ad_ltv330,ddz_ad_ltv331,ddz_ad_ltv332,ddz_ad_ltv333,ddz_ad_ltv334,ddz_ad_ltv335,ddz_ad_ltv336"
/root/code/tools/newdb_tools/ss_launcher.js  --path=/root/code/tools/newdb_tools/hxddz.bs/ltvn/ss_ddz_ad_ltv --log=/home/data/log/hxddz/ltvn --date=$first   --src=ddz_pay1 --topo="ddz_ad_ltv337,ddz_ad_ltv338,ddz_ad_ltv339,ddz_ad_ltv340,ddz_ad_ltv341,ddz_ad_ltv342,ddz_ad_ltv343,ddz_ad_ltv344,ddz_ad_ltv345,ddz_ad_ltv346,ddz_ad_ltv347,ddz_ad_ltv348"
/root/code/tools/newdb_tools/ss_launcher.js  --path=/root/code/tools/newdb_tools/hxddz.bs/ltvn/ss_ddz_ad_ltv --log=/home/data/log/hxddz/ltvn --date=$first   --src=ddz_pay1 --topo="ddz_ad_ltv349,ddz_ad_ltv350,ddz_ad_ltv351,ddz_ad_ltv352,ddz_ad_ltv353,ddz_ad_ltv354,ddz_ad_ltv355,ddz_ad_ltv356,ddz_ad_ltv357,ddz_ad_ltv358,ddz_ad_ltv359,ddz_ad_ltv360"

echo $first===ltvddz



/root/code/tools/newdb_tools/ss_launcher.js  --path=/root/code/tools/newdb_tools/hxddz.bs/ltvn/ss_trd_ad_ltv --log=/home/data/log/hxddz/ltvn --date=$first   --src=trd_pay1 --topo="trd_ad_ltv1,trd_ad_ltv2,trd_ad_ltv3,trd_ad_ltv4,trd_ad_ltv5,trd_ad_ltv6,trd_ad_ltv7,trd_ad_ltv8,trd_ad_ltv9,trd_ad_ltv10,trd_ad_ltv11,trd_ad_ltv12"
/root/code/tools/newdb_tools/ss_launcher.js  --path=/root/code/tools/newdb_tools/hxddz.bs/ltvn/ss_trd_ad_ltv --log=/home/data/log/hxddz/ltvn --date=$first   --src=trd_pay1 --topo="trd_ad_ltv13,trd_ad_ltv14,trd_ad_ltv15,trd_ad_ltv16,trd_ad_ltv17,trd_ad_ltv18,trd_ad_ltv19,trd_ad_ltv20,trd_ad_ltv21,trd_ad_ltv22,trd_ad_ltv23,trd_ad_ltv24"
/root/code/tools/newdb_tools/ss_launcher.js  --path=/root/code/tools/newdb_tools/hxddz.bs/ltvn/ss_trd_ad_ltv --log=/home/data/log/hxddz/ltvn --date=$first   --src=trd_pay1 --topo="trd_ad_ltv25,trd_ad_ltv26,trd_ad_ltv27,trd_ad_ltv28,trd_ad_ltv29,trd_ad_ltv30,trd_ad_ltv31,trd_ad_ltv32,trd_ad_ltv33,trd_ad_ltv34,trd_ad_ltv35,trd_ad_ltv36"
/root/code/tools/newdb_tools/ss_launcher.js  --path=/root/code/tools/newdb_tools/hxddz.bs/ltvn/ss_trd_ad_ltv --log=/home/data/log/hxddz/ltvn --date=$first   --src=trd_pay1 --topo="trd_ad_ltv37,trd_ad_ltv38,trd_ad_ltv39,trd_ad_ltv40,trd_ad_ltv41,trd_ad_ltv42,trd_ad_ltv43,trd_ad_ltv44,trd_ad_ltv45,trd_ad_ltv46,trd_ad_ltv47,trd_ad_ltv48"
/root/code/tools/newdb_tools/ss_launcher.js  --path=/root/code/tools/newdb_tools/hxddz.bs/ltvn/ss_trd_ad_ltv --log=/home/data/log/hxddz/ltvn --date=$first   --src=trd_pay1 --topo="trd_ad_ltv49,trd_ad_ltv50,trd_ad_ltv51,trd_ad_ltv52,trd_ad_ltv53,trd_ad_ltv54,trd_ad_ltv55,trd_ad_ltv56,trd_ad_ltv57,trd_ad_ltv58,trd_ad_ltv59,trd_ad_ltv60"
/root/code/tools/newdb_tools/ss_launcher.js  --path=/root/code/tools/newdb_tools/hxddz.bs/ltvn/ss_trd_ad_ltv --log=/home/data/log/hxddz/ltvn --date=$first   --src=trd_pay1 --topo="trd_ad_ltv61,trd_ad_ltv62,trd_ad_ltv63,trd_ad_ltv64,trd_ad_ltv65,trd_ad_ltv66,trd_ad_ltv67,trd_ad_ltv68,trd_ad_ltv69,trd_ad_ltv70,trd_ad_ltv71,trd_ad_ltv72"
/root/code/tools/newdb_tools/ss_launcher.js  --path=/root/code/tools/newdb_tools/hxddz.bs/ltvn/ss_trd_ad_ltv --log=/home/data/log/hxddz/ltvn --date=$first   --src=trd_pay1 --topo="trd_ad_ltv73,trd_ad_ltv74,trd_ad_ltv75,trd_ad_ltv76,trd_ad_ltv77,trd_ad_ltv78,trd_ad_ltv79,trd_ad_ltv80,trd_ad_ltv81,trd_ad_ltv82,trd_ad_ltv83,trd_ad_ltv84"
/root/code/tools/newdb_tools/ss_launcher.js  --path=/root/code/tools/newdb_tools/hxddz.bs/ltvn/ss_trd_ad_ltv --log=/home/data/log/hxddz/ltvn --date=$first   --src=trd_pay1 --topo="trd_ad_ltv85,trd_ad_ltv86,trd_ad_ltv87,trd_ad_ltv88,trd_ad_ltv89,trd_ad_ltv90,trd_ad_ltv91,trd_ad_ltv92,trd_ad_ltv93,trd_ad_ltv94,trd_ad_ltv95,trd_ad_ltv96"
/root/code/tools/newdb_tools/ss_launcher.js  --path=/root/code/tools/newdb_tools/hxddz.bs/ltvn/ss_trd_ad_ltv --log=/home/data/log/hxddz/ltvn --date=$first   --src=trd_pay1 --topo="trd_ad_ltv97,trd_ad_ltv98,trd_ad_ltv99,trd_ad_ltv100,trd_ad_ltv101,trd_ad_ltv102,trd_ad_ltv103,trd_ad_ltv104,trd_ad_ltv105,trd_ad_ltv106,trd_ad_ltv107,trd_ad_ltv108"
/root/code/tools/newdb_tools/ss_launcher.js  --path=/root/code/tools/newdb_tools/hxddz.bs/ltvn/ss_trd_ad_ltv --log=/home/data/log/hxddz/ltvn --date=$first   --src=trd_pay1 --topo="trd_ad_ltv109,trd_ad_ltv110,trd_ad_ltv111,trd_ad_ltv112,trd_ad_ltv113,trd_ad_ltv114,trd_ad_ltv115,trd_ad_ltv116,trd_ad_ltv117,trd_ad_ltv118,trd_ad_ltv119,trd_ad_ltv120"
/root/code/tools/newdb_tools/ss_launcher.js  --path=/root/code/tools/newdb_tools/hxddz.bs/ltvn/ss_trd_ad_ltv --log=/home/data/log/hxddz/ltvn --date=$first   --src=trd_pay1 --topo="trd_ad_ltv121,trd_ad_ltv122,trd_ad_ltv123,trd_ad_ltv124,trd_ad_ltv125,trd_ad_ltv126,trd_ad_ltv127,trd_ad_ltv128,trd_ad_ltv129,trd_ad_ltv130,trd_ad_ltv131,trd_ad_ltv132"
/root/code/tools/newdb_tools/ss_launcher.js  --path=/root/code/tools/newdb_tools/hxddz.bs/ltvn/ss_trd_ad_ltv --log=/home/data/log/hxddz/ltvn --date=$first   --src=trd_pay1 --topo="trd_ad_ltv133,trd_ad_ltv134,trd_ad_ltv135,trd_ad_ltv136,trd_ad_ltv137,trd_ad_ltv138,trd_ad_ltv139,trd_ad_ltv140,trd_ad_ltv141,trd_ad_ltv142,trd_ad_ltv143,trd_ad_ltv144"
/root/code/tools/newdb_tools/ss_launcher.js  --path=/root/code/tools/newdb_tools/hxddz.bs/ltvn/ss_trd_ad_ltv --log=/home/data/log/hxddz/ltvn --date=$first   --src=trd_pay1 --topo="trd_ad_ltv145,trd_ad_ltv146,trd_ad_ltv147,trd_ad_ltv148,trd_ad_ltv149,trd_ad_ltv150,trd_ad_ltv151,trd_ad_ltv152,trd_ad_ltv153,trd_ad_ltv154,trd_ad_ltv155,trd_ad_ltv156"
/root/code/tools/newdb_tools/ss_launcher.js  --path=/root/code/tools/newdb_tools/hxddz.bs/ltvn/ss_trd_ad_ltv --log=/home/data/log/hxddz/ltvn --date=$first   --src=trd_pay1 --topo="trd_ad_ltv157,trd_ad_ltv158,trd_ad_ltv159,trd_ad_ltv160,trd_ad_ltv161,trd_ad_ltv162,trd_ad_ltv163,trd_ad_ltv164,trd_ad_ltv165,trd_ad_ltv166,trd_ad_ltv167,trd_ad_ltv168"
/root/code/tools/newdb_tools/ss_launcher.js  --path=/root/code/tools/newdb_tools/hxddz.bs/ltvn/ss_trd_ad_ltv --log=/home/data/log/hxddz/ltvn --date=$first   --src=trd_pay1 --topo="trd_ad_ltv169,trd_ad_ltv170,trd_ad_ltv171,trd_ad_ltv172,trd_ad_ltv173,trd_ad_ltv174,trd_ad_ltv175,trd_ad_ltv176,trd_ad_ltv177,trd_ad_ltv178,trd_ad_ltv179,trd_ad_ltv180"
/root/code/tools/newdb_tools/ss_launcher.js  --path=/root/code/tools/newdb_tools/hxddz.bs/ltvn/ss_trd_ad_ltv --log=/home/data/log/hxddz/ltvn --date=$first   --src=trd_pay1 --topo="trd_ad_ltv181,trd_ad_ltv182,trd_ad_ltv183,trd_ad_ltv184,trd_ad_ltv185,trd_ad_ltv186,trd_ad_ltv187,trd_ad_ltv188,trd_ad_ltv189,trd_ad_ltv190,trd_ad_ltv191,trd_ad_ltv192"
/root/code/tools/newdb_tools/ss_launcher.js  --path=/root/code/tools/newdb_tools/hxddz.bs/ltvn/ss_trd_ad_ltv --log=/home/data/log/hxddz/ltvn --date=$first   --src=trd_pay1 --topo="trd_ad_ltv193,trd_ad_ltv194,trd_ad_ltv195,trd_ad_ltv196,trd_ad_ltv197,trd_ad_ltv198,trd_ad_ltv199,trd_ad_ltv200,trd_ad_ltv201,trd_ad_ltv202,trd_ad_ltv203,trd_ad_ltv204"
/root/code/tools/newdb_tools/ss_launcher.js  --path=/root/code/tools/newdb_tools/hxddz.bs/ltvn/ss_trd_ad_ltv --log=/home/data/log/hxddz/ltvn --date=$first   --src=trd_pay1 --topo="trd_ad_ltv205,trd_ad_ltv206,trd_ad_ltv207,trd_ad_ltv208,trd_ad_ltv209,trd_ad_ltv210,trd_ad_ltv211,trd_ad_ltv212,trd_ad_ltv213,trd_ad_ltv214,trd_ad_ltv215,trd_ad_ltv216"
/root/code/tools/newdb_tools/ss_launcher.js  --path=/root/code/tools/newdb_tools/hxddz.bs/ltvn/ss_trd_ad_ltv --log=/home/data/log/hxddz/ltvn --date=$first   --src=trd_pay1 --topo="trd_ad_ltv217,trd_ad_ltv218,trd_ad_ltv219,trd_ad_ltv220,trd_ad_ltv221,trd_ad_ltv222,trd_ad_ltv223,trd_ad_ltv224,trd_ad_ltv225,trd_ad_ltv226,trd_ad_ltv227,trd_ad_ltv228"
/root/code/tools/newdb_tools/ss_launcher.js  --path=/root/code/tools/newdb_tools/hxddz.bs/ltvn/ss_trd_ad_ltv --log=/home/data/log/hxddz/ltvn --date=$first   --src=trd_pay1 --topo="trd_ad_ltv229,trd_ad_ltv230,trd_ad_ltv231,trd_ad_ltv232,trd_ad_ltv233,trd_ad_ltv234,trd_ad_ltv235,trd_ad_ltv236,trd_ad_ltv237,trd_ad_ltv238,trd_ad_ltv239,trd_ad_ltv240"
/root/code/tools/newdb_tools/ss_launcher.js  --path=/root/code/tools/newdb_tools/hxddz.bs/ltvn/ss_trd_ad_ltv --log=/home/data/log/hxddz/ltvn --date=$first   --src=trd_pay1 --topo="trd_ad_ltv241,trd_ad_ltv242,trd_ad_ltv243,trd_ad_ltv244,trd_ad_ltv245,trd_ad_ltv246,trd_ad_ltv247,trd_ad_ltv248,trd_ad_ltv249,trd_ad_ltv250,trd_ad_ltv251,trd_ad_ltv252"
/root/code/tools/newdb_tools/ss_launcher.js  --path=/root/code/tools/newdb_tools/hxddz.bs/ltvn/ss_trd_ad_ltv --log=/home/data/log/hxddz/ltvn --date=$first   --src=trd_pay1 --topo="trd_ad_ltv253,trd_ad_ltv254,trd_ad_ltv255,trd_ad_ltv256,trd_ad_ltv257,trd_ad_ltv258,trd_ad_ltv259,trd_ad_ltv260,trd_ad_ltv261,trd_ad_ltv262,trd_ad_ltv263,trd_ad_ltv264"
/root/code/tools/newdb_tools/ss_launcher.js  --path=/root/code/tools/newdb_tools/hxddz.bs/ltvn/ss_trd_ad_ltv --log=/home/data/log/hxddz/ltvn --date=$first   --src=trd_pay1 --topo="trd_ad_ltv265,trd_ad_ltv266,trd_ad_ltv267,trd_ad_ltv268,trd_ad_ltv269,trd_ad_ltv270,trd_ad_ltv271,trd_ad_ltv272,trd_ad_ltv273,trd_ad_ltv274,trd_ad_ltv275,trd_ad_ltv276"
/root/code/tools/newdb_tools/ss_launcher.js  --path=/root/code/tools/newdb_tools/hxddz.bs/ltvn/ss_trd_ad_ltv --log=/home/data/log/hxddz/ltvn --date=$first   --src=trd_pay1 --topo="trd_ad_ltv277,trd_ad_ltv278,trd_ad_ltv279,trd_ad_ltv280,trd_ad_ltv281,trd_ad_ltv282,trd_ad_ltv283,trd_ad_ltv284,trd_ad_ltv285,trd_ad_ltv286,trd_ad_ltv287,trd_ad_ltv288"
/root/code/tools/newdb_tools/ss_launcher.js  --path=/root/code/tools/newdb_tools/hxddz.bs/ltvn/ss_trd_ad_ltv --log=/home/data/log/hxddz/ltvn --date=$first   --src=trd_pay1 --topo="trd_ad_ltv289,trd_ad_ltv290,trd_ad_ltv291,trd_ad_ltv292,trd_ad_ltv293,trd_ad_ltv294,trd_ad_ltv295,trd_ad_ltv296,trd_ad_ltv297,trd_ad_ltv298,trd_ad_ltv299,trd_ad_ltv300"
/root/code/tools/newdb_tools/ss_launcher.js  --path=/root/code/tools/newdb_tools/hxddz.bs/ltvn/ss_trd_ad_ltv --log=/home/data/log/hxddz/ltvn --date=$first   --src=trd_pay1 --topo="trd_ad_ltv301,trd_ad_ltv302,trd_ad_ltv303,trd_ad_ltv304,trd_ad_ltv305,trd_ad_ltv306,trd_ad_ltv307,trd_ad_ltv308,trd_ad_ltv309,trd_ad_ltv310,trd_ad_ltv311,trd_ad_ltv312"
/root/code/tools/newdb_tools/ss_launcher.js  --path=/root/code/tools/newdb_tools/hxddz.bs/ltvn/ss_trd_ad_ltv --log=/home/data/log/hxddz/ltvn --date=$first   --src=trd_pay1 --topo="trd_ad_ltv313,trd_ad_ltv314,trd_ad_ltv315,trd_ad_ltv316,trd_ad_ltv317,trd_ad_ltv318,trd_ad_ltv319,trd_ad_ltv320,trd_ad_ltv321,trd_ad_ltv322,trd_ad_ltv323,trd_ad_ltv324"
/root/code/tools/newdb_tools/ss_launcher.js  --path=/root/code/tools/newdb_tools/hxddz.bs/ltvn/ss_trd_ad_ltv --log=/home/data/log/hxddz/ltvn --date=$first   --src=trd_pay1 --topo="trd_ad_ltv325,trd_ad_ltv326,trd_ad_ltv327,trd_ad_ltv328,trd_ad_ltv329,trd_ad_ltv330,trd_ad_ltv331,trd_ad_ltv332,trd_ad_ltv333,trd_ad_ltv334,trd_ad_ltv335,trd_ad_ltv336"
/root/code/tools/newdb_tools/ss_launcher.js  --path=/root/code/tools/newdb_tools/hxddz.bs/ltvn/ss_trd_ad_ltv --log=/home/data/log/hxddz/ltvn --date=$first   --src=trd_pay1 --topo="trd_ad_ltv337,trd_ad_ltv338,trd_ad_ltv339,trd_ad_ltv340,trd_ad_ltv341,trd_ad_ltv342,trd_ad_ltv343,trd_ad_ltv344,trd_ad_ltv345,trd_ad_ltv346,trd_ad_ltv347,trd_ad_ltv348"
/root/code/tools/newdb_tools/ss_launcher.js  --path=/root/code/tools/newdb_tools/hxddz.bs/ltvn/ss_trd_ad_ltv --log=/home/data/log/hxddz/ltvn --date=$first   --src=trd_pay1 --topo="trd_ad_ltv349,trd_ad_ltv350,trd_ad_ltv351,trd_ad_ltv352,trd_ad_ltv353,trd_ad_ltv354,trd_ad_ltv355,trd_ad_ltv356,trd_ad_ltv357,trd_ad_ltv358,trd_ad_ltv359,trd_ad_ltv360"
echo $first===ltvtrd



first=`date -d "${first} +1 day" +%Y-%m-%d`
done

